/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package crud.backend.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the CRUD service. Represents a row in the &quot;CR_CRUD&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>crud.backend.model.impl.CRUDModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>crud.backend.model.impl.CRUDImpl</code>.
 * </p>
 *
 * @author liferay
 * @see CRUD
 * @generated
 */
@ProviderType
public interface CRUDModel extends BaseModel<CRUD> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a crud model instance should use the {@link CRUD} interface instead.
	 */

	/**
	 * Returns the primary key of this crud.
	 *
	 * @return the primary key of this crud
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this crud.
	 *
	 * @param primaryKey the primary key of this crud
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this crud.
	 *
	 * @return the uuid of this crud
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this crud.
	 *
	 * @param uuid the uuid of this crud
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the group ID of this crud.
	 *
	 * @return the group ID of this crud
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this crud.
	 *
	 * @param groupId the group ID of this crud
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the crud ID of this crud.
	 *
	 * @return the crud ID of this crud
	 */
	public long getCrudId();

	/**
	 * Sets the crud ID of this crud.
	 *
	 * @param crudId the crud ID of this crud
	 */
	public void setCrudId(long crudId);

	/**
	 * Returns the name of this crud.
	 *
	 * @return the name of this crud
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this crud.
	 *
	 * @param name the name of this crud
	 */
	public void setName(String name);

	/**
	 * Returns the department of this crud.
	 *
	 * @return the department of this crud
	 */
	@AutoEscape
	public String getDepartment();

	/**
	 * Sets the department of this crud.
	 *
	 * @param department the department of this crud
	 */
	public void setDepartment(String department);

	/**
	 * Returns the phone of this crud.
	 *
	 * @return the phone of this crud
	 */
	@AutoEscape
	public String getPhone();

	/**
	 * Sets the phone of this crud.
	 *
	 * @param phone the phone of this crud
	 */
	public void setPhone(String phone);

	/**
	 * Returns the email of this crud.
	 *
	 * @return the email of this crud
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this crud.
	 *
	 * @param email the email of this crud
	 */
	public void setEmail(String email);

	/**
	 * Returns the message of this crud.
	 *
	 * @return the message of this crud
	 */
	@AutoEscape
	public String getMessage();

	/**
	 * Sets the message of this crud.
	 *
	 * @param message the message of this crud
	 */
	public void setMessage(String message);

	@Override
	public CRUD cloneWithOriginalValues();

}